language: cpp

git:
  depth: 10

jobs:
  include:
  - stage: Unit tests
    name: Linux (c++17)
    os: linux
    dist: bionic
    env: COMPILER=g++-8
    services:
    - xvfb
    addons:
      apt:
        packages:
        - g++-8
        - libudev-dev
        - libxrandr-dev
        - libxcursor-dev
        - libgl1-mesa-dev
    cache:
      directories:
      - $HOME/SFML-2.5.1_LINUX
    script:
      - chmod +x tests/travis_linux_tests.sh
      - CXX=$COMPILER tests/travis_linux_tests.sh
    after_success: bash <(curl -s https://codecov.io/bash) -x gcov-8 -a "-s /home/travis/build/texus/TGUI -pr"

  - stage: Cross-platform tests
    name: Linux (c++14)
    os: linux
    dist: xenial
    env: COMPILER=g++-5
    addons:
      apt:
        packages:
        - g++-5
        - libudev-dev
        - libxrandr-dev
        - libxcursor-dev
        - libgl1-mesa-dev
    cache:
      ccache: true
      directories:
      - $HOME/SFML_LINUX
    script:
      - chmod +x tests/travis_linux.sh
      - CXX=$COMPILER tests/travis_linux.sh

  - name: Android
    language: android
    env:
    - NDK_DIR=$HOME/android-ndk
    android:
      components:
      - android-27
      - build-tools-26.0.2
    addons:
      apt:
        packages:
        - gradle
    cache:
      directories:
      - $HOME/sfml-cache
    script:
      - chmod +x tests/travis_android.sh
      - tests/travis_android.sh

  - name: macOS
    os: osx
    cache:
      directories:
      - $HOME/SFML_MACOS
    script:
      - chmod +x tests/travis_macos.sh
      - tests/travis_macos.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/66857e210e9200bcb6b7
    on_success: change
    on_failure: always
    on_start: never
